numServers: 5
numClients: 48

debug: true

persist: true

clientRequestTimeout: 1s

fd:
  pullInterval: 200ms
  timeout: 100ms

mailboxes:
  receiveChanSize: 10000
  dialTimeout: 50ms
  readTimeout: 50ms
  writeTimeout: 50ms

leaderElection:
  timeout: 150ms
  timeoutOffset: 150ms

appendEntriesSendInterval: 5ms

sharedResourceTimeout: 2ms

inputChanReadTimeout: 5ms

servers:
  1:
    mailboxAddr: "azbench-pgobench-1-vm-1:8000"
    mailboxAddr: "azbench-pgobench-1-vm-1:9000"
  
  2:
    mailboxAddr: "azbench-pgobench-1-vm-2:8000"
    mailboxAddr: "azbench-pgobench-1-vm-2:9000"
    
  3:
    mailboxAddr: "azbench-pgobench-1-vm-3:8000"
    mailboxAddr: "azbench-pgobench-1-vm-3:9000"

  4:
    mailboxAddr: "azbench-pgobench-1-vm-4:8000"
    mailboxAddr: "azbench-pgobench-1-vm-4:9000"

  5:
    mailboxAddr: "azbench-pgobench-1-vm-5:8000"
    mailboxAddr: "azbench-pgobench-1-vm-5:9000"

clients:
  1: "azbench-pgobench-1-vm-client:8001"
  2: "azbench-pgobench-1-vm-client:8002"
  3: "azbench-pgobench-1-vm-client:8003"
  4: "azbench-pgobench-1-vm-client:8004"
  5: "azbench-pgobench-1-vm-client:8005"
  6: "azbench-pgobench-1-vm-client:8006"
  7: "azbench-pgobench-1-vm-client:8007"
  8: "azbench-pgobench-1-vm-client:8008"
  9: "azbench-pgobench-1-vm-client:8009"
  10: "azbench-pgobench-1-vm-client:8010"
  11: "azbench-pgobench-1-vm-client:8011"
  12: "azbench-pgobench-1-vm-client:8012"
  13: "azbench-pgobench-1-vm-client:8013"
  14: "azbench-pgobench-1-vm-client:8014"
  15: "azbench-pgobench-1-vm-client:8015"
  16: "azbench-pgobench-1-vm-client:8016"
  17: "azbench-pgobench-1-vm-client:8017"
  18: "azbench-pgobench-1-vm-client:8018"
  19: "azbench-pgobench-1-vm-client:8019"
  20: "azbench-pgobench-1-vm-client:8020"
  21: "azbench-pgobench-1-vm-client:8021"
  22: "azbench-pgobench-1-vm-client:8022"
  23: "azbench-pgobench-1-vm-client:8023"
  24: "azbench-pgobench-1-vm-client:8024"
  25: "azbench-pgobench-1-vm-client:8025"
  26: "azbench-pgobench-1-vm-client:8026"
  27: "azbench-pgobench-1-vm-client:8027"
  28: "azbench-pgobench-1-vm-client:8028"
  29: "azbench-pgobench-1-vm-client:8029"
  30: "azbench-pgobench-1-vm-client:8030"
  31: "azbench-pgobench-1-vm-client:8031"
  32: "azbench-pgobench-1-vm-client:8032"
  33: "azbench-pgobench-1-vm-client:8033"
  34: "azbench-pgobench-1-vm-client:8034"
  35: "azbench-pgobench-1-vm-client:8035"
  36: "azbench-pgobench-1-vm-client:8036"
  37: "azbench-pgobench-1-vm-client:8037"
  38: "azbench-pgobench-1-vm-client:8038"
  39: "azbench-pgobench-1-vm-client:8039"
  40: "azbench-pgobench-1-vm-client:8040"
  41: "azbench-pgobench-1-vm-client:8041"
  42: "azbench-pgobench-1-vm-client:8042"
  43: "azbench-pgobench-1-vm-client:8043"
  44: "azbench-pgobench-1-vm-client:8044"
  45: "azbench-pgobench-1-vm-client:8045"
  46: "azbench-pgobench-1-vm-client:8046"
  47: "azbench-pgobench-1-vm-client:8047"
  48: "azbench-pgobench-1-vm-client:8048"